config/routes.rb
Rails.application.routes.draw do
  resources :campaigns do
    collection do
      post :import
      get :criteria_keywords
    end

    resources :ad_groups, only: [:index, :show] do
      resources :keywords, only: [:index, :show]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "campaigns#index"
end

app/models/ad_group.rb
class AdGroup < ApplicationRecord
	belongs_to :campaign
	has_many :keywords
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	has_many :ad_groups
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :ad_group
end

app/controllers/ad_groups_controller.rb
class AdGroupsController < ApplicationController
  before_action :set_context
  before_action :set_ad_group, only: %i[ show ]

  # GET /campaigns or /campaigns.json
  def index
    @ad_groups = @campaign.ad_groups
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
  end

  private

  def set_context
    @campaign = Campaign.find(params[:campaign_id])
  end


  def set_ad_group
    @ad_group = @campaign.ad_groups.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully created." }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: "Campaign was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    file = params[:file]
    xlsx = Roo::Excelx.new(file.path)
    xlsx.default_sheet = 'Sponsored Products Campaigns'
    header = xlsx.row(1)
    (2..xlsx.last_row).each do |i|
      row = Hash[[header, xlsx.row(i)].transpose]
      @campaign = Campaign.find_or_create_by(id: row['Campaign Id'], name: row['Campaign Name'], budget: row['Daily Budget'], start_date: Date.parse(row['Start Date'])) if(row['Entity'].eql? 'Campaign')
      @ad_group = @campaign.ad_groups.find_or_create_by(id: row['Ad Group Id'], name: row['Ad Group Name'], default_bid: row['Ad Group Default Bid']) if(row['Entity'].eql? 'Ad Group')
      @ad_group.keywords.find_or_create_by(id: row['Keyword Id (Read only)'], text: row['Keyword Text'], bid: row['Bid'], match_type: row['Match Type'], impressions: row['Impressions'], clicks: row['Clicks'], ctr: row['Click-through Rate'],
                               spend: row['Spend'], sales: row['Sales'], orders: row['Orders'], units: row['Units'], cr: row['Coversion Rate'],
                               acos: row['ACOS'], cpc: row['CPC'], roas: row['ROAS']) if(row['Entity'].eql? 'Keyword')
    end
    redirect_to campaigns_path, notice: "Campaigns Imported Successfully"
  end

  def criteria_keywords
    @keywords = Keyword.includes(ad_group: :campaign)
                       .joins(:ad_group)
                       .where("ad_groups.name LIKE ?", "%NB%")
                       .where(spend: 1..Float::INFINITY, sales: 0)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.fetch(:campaign, {})
    end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_context
  before_action :set_keyword, only: %i[ show ]

  def index
    @keywords = @ad_group.keywords
  end

  def show
  end

  private

  def set_context
    @campaign = Campaign.find(params[:campaign_id])
    @ad_group = @campaign.ad_groups.find(params[:ad_group_id])
  end

  def set_keyword 
    @keyword = @ad_group.keywords.find(params[:id])
  end
end

app/helpers/ad_group_helper.rb
module AdGroupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/keyword_helper.rb
module KeywordHelper
end

app/views/ad_groups/_ad_group.html.erb
<tr id="<%= dom_id ad_group %>" class= 'text-center'>
  <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
    <%= ad_group.id %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= ad_group.name %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= ad_group.default_bid %></td>
  <td class="whitespace-nowrap px-4 py-2">
    <% if action_name != "show" %>
      <%= link_to "Show Keywords", campaign_ad_group_keywords_path(ad_group.campaign, ad_group), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </td>
</tr>

app/views/ad_groups/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ad Groups</h1>
    <%= link_to 'Back to campaigns', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
      <thead class="">
        <tr>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Id
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Name
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Default Bid
          </th>
          <th class="px-4 py-2"></th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-200">
        <%= render @ad_groups %>
      </tbody>
    </table>
  </div>
</div>

app/views/campaigns/_campaign.html.erb
<tr id="<%= dom_id campaign %>" class= 'text-center'>
  <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
    <%= campaign.id %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= campaign.name %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= campaign.start_date %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= number_to_currency(campaign.budget) %></td>
  <td class="whitespace-nowrap px-4 py-2">
    <% if action_name != "show" %>
      <%= link_to "Show Ad Groups", campaign_ad_groups_path(campaign), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </td>
</tr>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, class: "contents") do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
        <% campaign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/campaigns/criteria_keywords.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Criteria Keywords</h1>
      <%= link_to 'Back to Campaigns', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
      <thead class="">
        <tr>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
				    Campaign Name</th>
				    <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
				    Ad Group Name</th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Id
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Text
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            bid
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Match Type
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Spent
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Sales
          </th>
          <th class="px-4 py-2"></th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-200">
        <%= render @keywords %>
      </tbody>
    </table>
  </div>
</div>

app/views/campaigns/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing campaign</h1>

  <%= render "form", campaign: @campaign %>

  <%= link_to "Show this campaign", @campaign, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to campaigns", campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/campaigns/index.html.erb
<div class="w-full">
  <% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex flex-col items-center justify-center">
    <%= form_tag import_campaigns_path, multipart: true, class: "max-w-lg w-full" do %>
    <div class="flex flex-col items-center justify-center px-6 py-4 bg-gray-100 rounded-lg shadow-md border border-gray-200">
      <label for="file" class="text-lg font-medium text-gray-700 mb-2">Select an XLSX file to import:</label>
      <div class="relative overflow-hidden">
        <%= file_field_tag :file, class: "absolute inset-0 w-full h-full opacity-0 cursor-pointer" %>
        <div class="px-4 py-2 bg-white rounded-lg shadow-md border border-gray-200 text-gray-500 hover:text-gray-700 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all duration-300 ease-in-out cursor-pointer">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
          </svg>
          <span class="text-sm font-medium">Choose a file</span>
        </div>
      </div>
    </div>
    <button type="submit" class="mt-4 bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded-lg shadow-md transition-all duration-300 ease-in-out">
      Import
    </button>
    <% end %>
  </div>
  <%= link_to "Show Keywords based on criteria", criteria_keywords_campaigns_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Campaigns</h1>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
      <thead class="">
        <tr>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Id
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Name
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Start Date
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Budget
          </th>
          <th class="px-4 py-2"></th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-200">
        <%= render @campaigns %>
      </tbody>
    </table>
  </div>
</div>

app/views/campaigns/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New campaign</h1>

  <%= render "form", campaign: @campaign %>

  <%= link_to 'Back to campaigns', campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/campaigns/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @campaign %>

    <%= link_to 'Edit this campaign', edit_campaign_path(@campaign), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this campaign', campaign_path(@campaign), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to campaigns', campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/keywords/_keyword.html.erb
<tr id="<%= dom_id keyword %>" class= 'text-center'>
  <% if action_name == 'criteria_keywords' %>
    <% ad_group = keyword.ad_group %>
    <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
    <%= keyword.ad_group.campaign.name %></td>
    <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
    <%= keyword.ad_group.name %></td>
  <% end %>
  <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
    <%= keyword.id %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= keyword.text %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= keyword.match_type %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= keyword.spend %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= keyword.sales %></td>
  <td class="whitespace-nowrap px-4 py-2">
  <% if action_name != "show" %>
    <% if @campaign.present? %>
      <%= link_to "Show Details", campaign_ad_group_keyword_path(@campaign, @ad_group, keyword), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% else %>
      <%= link_to "Show Details", campaign_ad_group_keyword_path(ad_group.campaign, ad_group, keyword), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  <% end %>

  </td>
</tr>

app/views/keywords/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Keywords</h1>
    <% if @campaign.present? %>
    <%= link_to 'Back to Ad Groups', campaign_ad_groups_path(@campaign), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% else %>
      <%= link_to 'Back to Campaigns', campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
      <thead class="">
        <tr>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Id
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Text
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            bid
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Match Type
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Spent
          </th>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
            Sales
          </th>
          <th class="px-4 py-2"></th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-200">
        <%= render @keywords %>
      </tbody>
    </table>
  </div>
</div>

app/views/keywords/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto justify-center">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class=" bg-slate-100 p-10">
	    <% @keyword.attributes.each do |k, v| %>
			  <p class="my-5">
			    <span><strong class="font-medium mb-1"><%= k.capitalize %>:</strong> <%= v %></span>
			  </p>
			<% end %>
    </div>
	 	<%= link_to 'Back to keywords', request.referer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonAdManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>